### ISSUE TITLE
Local variable 'term' might be referenced before assignment in library.py

### ISSUE THREAD

**Issue by carlosm-silva** [sibirica/SPIDER_discrete#5]
In `library.py` class `Equation` special method `eq`, we have the following code:
```
      for coeff, ot in zip(self.coeffs, other.coeffs):
            if term != ot:
                return False
```
In this scope `term` is undefined.

**Comment by sibirica** [comment]
I don't know how I implemented that method so badly but it's fixed to a one-liner.
